"""
Máquina de estados dos pedidos (mesma que definimos na arquitetura).
"""

NOVO = "NOVO"
ATENDIMENTO = "ATENDIMENTO"
CARRINHO = "CARRINHO"
AGUARDANDO_CONFIRMACAO = "AGUARDANDO_CONFIRMACAO"
AGUARDANDO_DADOS = "AGUARDANDO_DADOS"
AGUARDANDO_PAGAMENTO = "AGUARDANDO_PAGAMENTO"
COMPROVANTE_RECEBIDO = "COMPROVANTE_RECEBIDO"
AGUARDANDO_CONFERENCIA = "AGUARDANDO_CONFERENCIA"
PAGAMENTO_CONFIRMADO = "PAGAMENTO_CONFIRMADO"
SEPARANDO = "SEPARANDO"
PRONTO = "PRONTO"
ENVIADO = "ENVIADO"
FINALIZADO = "FINALIZADO"
CANCELADO = "CANCELADO"
HUMANO = "HUMANO"
PAGAMENTO_NAO_CONFIRMADO = "PAGAMENTO_NAO_CONFIRMADO"

ABERTOS = [
    NOVO, ATENDIMENTO, CARRINHO, AGUARDANDO_CONFIRMACAO, AGUARDANDO_DADOS,
    AGUARDANDO_PAGAMENTO, COMPROVANTE_RECEBIDO, AGUARDANDO_CONFERENCIA,
    PAGAMENTO_CONFIRMADO, SEPARANDO, PRONTO, HUMANO, PAGAMENTO_NAO_CONFIRMADO,
]

PAGAMENTO_PENDENTE = "PENDENTE"
PAGAMENTO_CONFIRMADO_STATUS = "CONFIRMADO"
PAGAMENTO_RECUSADO = "RECUSADO"
