from enum import Enum


class StatusPedido(str, Enum):
    NOVO = "NOVO"
    ATENDIMENTO = "ATENDIMENTO"
    CARRINHO = "CARRINHO"
    AGUARDANDO_CONFIRMACAO = "AGUARDANDO_CONFIRMACAO"
    AGUARDANDO_DADOS = "AGUARDANDO_DADOS"
    AGUARDANDO_PAGAMENTO = "AGUARDANDO_PAGAMENTO"
    COMPROVANTE_RECEBIDO = "COMPROVANTE_RECEBIDO"
    AGUARDANDO_CONFERENCIA = "AGUARDANDO_CONFERENCIA"
    PAGAMENTO_CONFIRMADO = "PAGAMENTO_CONFIRMADO"
    SEPARANDO = "SEPARANDO"
    PRONTO = "PRONTO"
    ENVIADO = "ENVIADO"
    FINALIZADO = "FINALIZADO"
    CANCELADO = "CANCELADO"
    HUMANO = "HUMANO"
    PAGAMENTO_NAO_CONFIRMADO = "PAGAMENTO_NAO_CONFIRMADO"

    @property
    def esta_aberto(self) -> bool:
        return self not in (StatusPedido.ENVIADO, StatusPedido.FINALIZADO, StatusPedido.CANCELADO)
